Accepting Built-In Arrays
CommitThis/zip-iterator pull request #4
Opened 2024-12-15 21:33 UTC by TobiasWallner

zip_tuple can now iterate over built in arrays too and does not need containers like `std::vector<int>`

2024-12-16 02:36 UTC, CommitThis requested changes
Hi @TobiasWallner, thanks for your PR. Assuming by "built-in arrays", you mean things like `int[N]`, I would definitely see the utility in the change. However, I can't accept it at the moment on account of the reference removal on what I had called the "access type". See code review comments for details.

I've added a branch with a more extensive set of tests and actually used googletest @ [wip-builtin-array](https://github.com/CommitThis/zip-iterator/tree/wip-builtin-array) (with none of your changes) for you to rebase on should you wish to continue.

2024-12-16 02:36 UTC, CommitThis commented on zip_tuple.hpp
> +using select_access_type_for = std::remove_reference_t<decltype(*std::declval<Iter&>())>;
This removes the reference from the dereferenced iterator; the intention of the iterator was such that you could perform operations like:

```cpp
for (auto && [x, y, z] : c9::zip(a, b, c)) {
    x = y + z;
}
```
Where the iterator for some iterable `a` is assigned to via `x`.

Your change here prevents that. However, I can concede that the original implementation is a bit of a kludge on account of assuming `Iter` would be some iterator object, rather than some iterator-like (e.g. some `T*`). This would be one of the barriers to accepting raw arrays, assuming that this was your intention with the PR. And of course specialising on `std::vector<bool>` adds a bit of noise.

I would propose that this instead be changed to:

```cpp
template <typename Iter>
using select_access_type_for = typename std::iterator_traits<Iter>::reference;
```

This would also have the benefit of allowing dereferencing _to_ the proxy class for `std::vector<bool>`.

Unless of course there was some other motivating factor for removing the reference in the first place?

2024-12-16 02:36 UTC, CommitThis commented on zip_tuple.hpp
> +#pragma once
Oops

2024-12-16 02:36 UTC, CommitThis commented on zip_tuple.hpp
> +using select_iterator_for = decltype(std::begin(std::declval<T&>()));
Grand.

2024-12-16 02:36 UTC, CommitThis commented on zip_two.hpp
> +#pragma once
Oops

2024-12-20 20:29 UTC, TobiasWallner commented on zip_tuple.hpp
> +using select_iterator_for = decltype(std::begin(std::declval<T&>()));
Grand as in granted, or grand as is your grand comment above concerning line 19 to 20 of the original / 16 of the new?

2024-12-20 20:39 UTC, TobiasWallner commented
Thanks for the notice, I will see to testing it with google tests.

My main concern was that it, as you correctly noticed, to accept types of `int (&)[N]`. 
Additionally, I would also have wanted to support for custom iterateable objects that do not comform to the STD and thus not have `::value_type` or `::reference` as public type aliases or don't work with `std::iterator_traits<Iter>`.

I would prefer this, because it allows for quicker developement when you just wanna do something quick and easy. Also everyone comeing from the python world using your library would love for it to work quick and easy for everything that you throw at it. This would also be less of a barrier for less cpp-savy people.

2024-12-20 20:41 UTC, TobiasWallner commented on zip_tuple.hpp
> +using select_access_type_for = std::remove_reference_t<decltype(*std::declval<Iter&>())>;
how about:
```cpp
using select_value_type_for = std::remove_reference_t<decltype(*std::declval<Iter&>())>;
using select_access_type_for = select_value_type_for &;
```
or
```cpp
using select_value_type_for = decltype(*std::declval<Iter&>());
```
?

2024-12-20 20:50 UTC, TobiasWallner commented on zip_tuple.hpp
> +using select_access_type_for = std::remove_reference_t<decltype(*std::declval<Iter&>())>;
Just tested this with:
```cpp
std::vector<bool> A {true, false, false, false, true};
std::vector<bool> B {false, true, false, false, true};
bool C[] = {false, true, true, false, true};

for(auto && [a, b, c] : c9::zip(A, B, C)){
    a = b || c;
}

for(bool a : A){
    fmt::print("a: {}\n", a);
}
```
and it works.  
output:
```
a: false
a: true
a: true
a: false
a: true
```

2024-12-20 21:06 UTC, CommitThis commented on zip_tuple.hpp
> +using select_iterator_for = decltype(std::begin(std::declval<T&>()));
"Grand" as in great, good choice. I needn't have commented, really.

2024-12-20 21:52 UTC, CommitThis commented
Thanks for clarifying what you're trying to achieve.

Out of curiosity, do you have an example of a thing that is iterable, but does not have iterator traits defined? The `zip_iterator<Iters...>` relies on the fact that the iterators it holds also satisfy a requirement for, at the very least, to be incrementable [1], and it would stand to reason if a thing has `begin` and `end` that returns an iterable of some sort, that includes increment operators and dereference operators, that they too should support iterator traits in some way [2].

[1]: I should have probably used `(++args)` (so explicitly prefix incrementable) on line 56. Nevermind.
[2]: I'm generally thinking about legacy iterators; when I wrote the code (some years ago) I didn't have much knowledge of "concepts", and this might be a case where they could be useful.

2024-12-21 19:57 UTC, TobiasWallner commented
The most important thing for me is that built-in arrays `int(&)[N]` or `int[N]` are supportet. I would also be happy to reduce this PR to that note.

The addition of getting the iterator traits not from predifined 
```cpp
using value_type = ...
using reference = ...
```
but let the compiler figure it out from the return type of the dereference operation was just a sugestion. If you do not want this and prefere the standard way I can understand that. 

Do you want me to change it to your suggestion?
> ```cpp
> template <typename Iter>
> using select_access_type_for = typename std::iterator_traits<Iter>::reference;
> ```
instead of 
```cpp
template <typename Iter>
using select_value_type_for = decltype(*std::declval<Iter&>());
```
?

2024-12-21 20:03 UTC, CommitThis commented
Yeh, I think I would prefer it if was `iterator_traits<Iter>::reference` because at least then I know what it is (e.g. `[const] value_type &`, some proxy). It'd probably be easier to debug if something goes wrong. It also implies in some way that the intention is it's supposed to work with iterators in general.

So if you you make the change as requested, I will happily accept the PR. If you don't want to rebase or merge against the branch with tests first, I think I should be able to do that as you've given me permission to edit it, I think?

2025-01-17 17:15 UTC, TobiasWallner commented
Sry for the long wait ... hope you hade nice holidays too.

2025-01-20 16:08 UTC, merged

2025-01-20 16:11 UTC, CommitThis commented
Hi @TobiasWallner, hope you had a grand holiday also. It's all merged now. Thanks for your help!